import { jsx as _jsx } from "react/jsx-runtime";
import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { AuthProvider } from './context/RealAuthContext';
import { ThemeProvider } from './context/ThemeProvider';
const client = new QueryClient();
const root = createRoot(document.getElementById('root'));
root.render(_jsx(React.StrictMode, { children: _jsx(QueryClientProvider, { client: client, children: _jsx(AuthProvider, { children: _jsx(ThemeProvider, { children: _jsx(BrowserRouter, { basename: "/support-me-site", children: _jsx(App, {}) }) }) }) }) }));
